name: Quick Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Quick Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test FastAPI import
      run: |
        python -c "
        from app.main import app
        print('✅ FastAPI app imported successfully')
        print(f'App title: {app.title}')
        print(f'App version: {app.version}')
        "
        
    - name: Test configuration
      run: |
        python -c "
        from app.config import settings
        print('✅ Configuration loaded successfully')
        print(f'App name: {settings.app_name}')
        print(f'App version: {settings.app_version}')
        "
        
    - name: Success message
      run: |
        echo "🎉 Quick test completed successfully!"
        echo "All basic imports and configurations are working"
